### ISSUE TITLE
Git version exits with SIGABRT right after launch on x86_64 Arch Linux

### ISSUE THREAD

**Issue by J5lx** [GlPortal/glPortal#10]
When I just tried to run the git version of GlPortal on Arch Linux, I got this output:

```
File loaded.
Vertex shader compiled successfully
Fragment shader compiled successfully
Shader program linked successfully
Vertex shader compiled successfully
Fragment shader compiled successfully
Vertex shader compiled successfully
Fragment shader compiled successfully
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

I installed GlPortal using this PKGBUILD which I put together myself: <https://aur.archlinux.org/packages/gl/glportal-git/PKGBUILD>. Compared with the instructions in COMPILE.org it uses out-of-source builds and a custom install prefix.

You can find the core dump dumped using `coredumpctl dump` at <http://ge.tt/3zwLU582/v/0> (since the original dump was too big for Gett I compressed it "a bit" using xz).

It would be really nice if this could be resolved!

**Comment by hhirsch** [comment]
@J5lx can you check if this commit fixes the out of range error you got?

**Comment by J5lx** [comment]
No, unfortunately it doesn't :/

Output:

```
File loaded.
Vertex shader compiled successfully
Fragment shader compiled successfully
Shader program linked successfully
Vertex shader compiled successfully
Fragment shader compiled successfully
Vertex shader compiled successfully
Fragment shader compiled successfully
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
zsh: abort (core dumped)  glportal
```

Dump: <http://ge.tt/8HgKyV92/v/0>

**Comment by J5lx** [comment]
I just ran an updated build of the game and now the issue is gone.

**Comment by hhirsch** [comment]
@J5lx Thank you for reporting.
