### ISSUE TITLE
Provided VS 2017 solution doesn't compile

### ISSUE THREAD

**Issue by mesosurface** [GlPortal/glPortal#107]
The VS 2017 solution provided [here](https://bintray.com/glportal/generic/GlPortal-VS2017-Solution), which is horribly disfigured and malformed, does not compile. Not even in the suggested Release + x86 configuration.

Cheers.

**Comment by hhirsch** [comment]
@mesosurface Thank you for reporting. We currently have somebody actively working on improving instructions and the solution for VS.

**Comment by hhirsch** [comment]
@mesosurface The solution we provide did not change, so how is this solved?

**Comment by kungfooman** [comment]
@mesosurface Still wanna try? Made a complete new solution: https://github.com/kungfooman/glportal-vs

**Comment by hhirsch** [comment]
@mesosurface Re-Open if the problem still occurs.
