### ISSUE TITLE
Convert old text format data into the new xml format

### ISSUE THREAD

**Issue by hhirsch** [GlPortal/glPortal#134]
Download https://bintray.com/glportal/glportal_releases/GlPortal/0.1-pre#files and see the maps in the data directory. Get aquainted with the new map format as specified here https://github.com/GlPortal/specification/tree/master/formats/map . For some examples look at the maps here https://github.com/GlPortal/glportal-data/tree/master/maps 

Using the knowledge of how the map format has changed write a converter from old format to the new one. You can use Perl, Python or any other language you see fit. You can also resurrect the old map parser from the sources but that might overcomplicate matters.

**Comment by Collaken** [comment]
I'm on it!
