### ISSUE TITLE
AUR Package Maintainence

### ISSUE THREAD

**Issue by lastweakness** [GlPortal/glPortal#142]
Hi,  
I was the one who packaged the stable AUR package at first (glportal, not glportal-git). But unfortunately, i had to stop maintaining it and did not disown the package until today. I'm sorry for the inconvenience but it would be great if someone could adopt the package now.  
Thanks

**Comment by lastweakness** [comment]
This relies on #141 being fixed, I guess.

**Comment by ElementW** [comment]
Since I'm back and use Arch as a daily driver I could maintain it.
