### ISSUE TITLE
Make VS a first class citizen

### ISSUE THREAD

**Issue by hhirsch** [GlPortal/glPortal#154]
- [ ] Advertise for VS developers
- [ ] Host DLLs on Bintray
- [ ] Update glportal-vs
- [ ] Update Documentation
- [ ] Try VS for Linux

**Comment by hhirsch** [comment]
@kungfooman This might be interesting to you. I'll give VS a spin myself and will advertise to find more VS devs.

**Comment by kungfooman** [comment]
I would really like to, but I have so many other projects to work on (mostly gamedev-related aswell, but focus on WebGL). Maybe one day some stuff can be used together (like map editor based on id-software/q3radiant), for people who don't like Blender so much.

On another note, for some reason my Windows git fails to clone all submodules for glportal-vs:

```
kung@DESKTOP-NITUN3M MINGW64 /s/glportal-vs/glportal ((b5ab026...))
$ git submodule update --recursive
error: Server does not allow request for unadvertised object 3922ea8953b9462b4194258eb591d83aae8cfcec
Fetched in submodule path 'data', but it did not contain 3922ea8953b9462b4194258eb591d83aae8cfcec. Direct fetching of that commit failed.

```
