### ISSUE TITLE
make error in M1 Mac

### ISSUE THREAD

**Issue by Tekh-ops** [GlPortal/glPortal#183]
**Describe the bug**

clang: error: unsupported argument '-mimplicit-it=always' to option 'Wa,'
make[2]: *** [external/RadixEngine/external/AngelScript/sdk/angelscript/projects/cmake/CMakeFiles/angelscript.dir/__/__/source/as_callfunc_arm_gcc.S.o] Error 1
make[1]: *** [external/RadixEngine/external/AngelScript/sdk/angelscript/projects/cmake/CMakeFiles/angelscript.dir/all] Error 2
make: *** [all] Error 2

**To Reproduce**
1. Compile in M1 Mac
2. Follow the COMPILE.md instructions 
3. got an error in Assembly flags
4. 

**Expected behavior**
According to COMPILE.md, it should build the glPortal Executable.

**Screenshots**

![ezgif-3-7f5e60d73c60](https://user-images.githubusercontent.com/78523194/135633920-6b366faa-474a-471e-a695-c41ba2a86945.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.6

**Additional context**

I followed the COMPILE.md correctly.
And I already installed the git submodules.

**Comment by hhirsch** [comment]
Are you sure it is fixed? The build should be broken on many levels atm.

**Comment by Pkill-MyDaemons** [comment]
I have the exact same issue, except that I am on macOS 26 Tahoe (Current) 

@Tekh-ops Do you have a quick fix?

<img width="588" height="411" alt="Image" src="https://github.com/user-attachments/assets/818aceae-fc2f-4c0a-8c1e-41d25443ea41" />

**Comment by hhirsch** [comment]
Wasn't able to compile.
