### ISSUE TITLE
Incorrect File Paths for Building on Windows

### ISSUE THREAD

**Issue by amiruqdah** [GlPortal/glPortal#34]
After growing increasingly frustrated with not being able to build from source on Windows I decided to take a look at the cmake [folder](/GlPortal/glPortal/tree/master/cmake) and found that it was **not** setup to look for dependencies on Windows machines correctly. If you look at any of the files, you can already see that the FIND and INCLUDE path's are set up relative to the folder structure of a Linux Machine. In fact, the last changes made to these files was a feature fix that allowed them to be compiled (exclusively) on GNU/Linux.

I see that there are two ways to fix this. 

- Include the dependencies themselves (and search relative to GLPortal)
- Attempt to build around the Cygwin enviornment.

There is also the possibility of me taking a look at editing the files so that they work more readily on a Windows Machine. 

@hhirsch If the developer that uses VS on Windows is still around, can you please mention him here in this issue and perhaps we can both work together to find a solution? 

Once I figure out how to build it on my machine, I will update the compile [instructions](/GlPortal/glPortal/blob/master/COMPILE.md) to help out others that might be developing on a Windows machine. 

Let me know what you think and we can move on to fix this issue.

**Comment by SGOrava** [comment]
OK, i will try to try to compile it under Win XP in VirtualBox... i don't understand where is the problem...

**Comment by hhirsch** [comment]
@amiruqdah Thank you. Julian did builds on VS his handle is @JulianThijssen .

**Comment by amiruqdah** [comment]
@SGOrava If you get it working, let me know!

**Comment by hhirsch** [comment]
The code is cross platform. Go ahead and compile it on windows. We love to accept PRs with visual studio project files or cross platform cmakelist files. We will support any serious effort to compile the game on windows with all the support we can give. I am also very actively looking for a windows maintainer. I am making this my personal responsibility.

**Comment by hhirsch** [comment]
You can find an experimental binary here https://github.com/SGOrava/sgorava.github.io/tree/master/data

**Comment by SGOrava** [comment]
@amiruqdah Hello, i was able to compile GlPortal for windows with mingw-w64 under linux, it is easy.

I will wrote something how i built it...

**Comment by hhirsch** [comment]
I remember using this and crashing into a wall https://cmake.org/Wiki/CmakeMingw

**Comment by SGOrava** [comment]
@hhirsch i used "mingw-cmake" from AUR, i did not have to set anything...

**Comment by hhirsch** [comment]
Closed due to lack of interest of the OP. Re-open if any new questions arise.
