### ISSUE TITLE
cmake can't find libxml2

### ISSUE THREAD

**Issue by nifker** [GlPortal/glPortal#35]
I have installed libxml with "# pacman -Syu libxml" and installed the version 2.6

log is the following: http://pastebin.com/0hgL2qJp

**Comment by hhirsch** [comment]
@nifker Hello. The game uses libxml2. https://www.archlinux.org/packages/?q=libxml2

**Comment by SGOrava** [comment]
is it really libxml2 or it is tinyxml2 ??

GlPortal depends on TinyXML2
install `tinyxml2` from AUR
https://aur.archlinux.org/packages/tinyxml2/

**Comment by hhirsch** [comment]
@SGOrava Yep, you are right. @nifker

**Comment by nifker** [comment]
pacman says I already installed it: https://www.parabola.nu/packages/extra/x86_64/libxml2/

**Comment by nifker** [comment]
https://www.parabola.nu/packages/?sort=&q=tinyxml2&maintainer=&flagged=

**Comment by nifker** [comment]
Now I got this cmake error:
CMake Error at CMakeLists.txt:42 (add_subdirectory):
  The source directory

    /home/user/Desktop/Compiling/glPortal/data

  does not contain a CMakeLists.txt file.

**Comment by hhirsch** [comment]
@nifker Are you even following https://github.com/GlPortal/glPortal/blob/master/COMPILE.md ?
You don't seem to have initialized or updated the submodules.

**Comment by nifker** [comment]
Oh forgot that thanks.
