### ISSUE TITLE
Method jump() of KinematicCharacterController class is outdated (bullet 2.85-1)

### ISSUE THREAD

**Issue by Sakerdot** [GlPortal/glPortal#49]
Basically this jump method is overriding btKineticCharacterController one which has changed in version 2.85-1 (https://github.com/bulletphysics/bullet3/commit/626a913866158e5956cfa2ae7f5f6350e99d783e), making the compiler complain and giving an error.

**Comment by hhirsch** [comment]
@Sakerdot We are currently using Bullet 2.83.

**Comment by hhirsch** [comment]
@Sakerdot Re-Open if this is still an issue for some reason.

**Comment by Geertiebear** [comment]
Bullet updated recently, that's propbably why it's breaking. @Sakerdot what distro are you on?

**Comment by SGOrava** [comment]
Now we can compile engine with Bullet v2.85..
But this should be done more properly in order to use new features.

**Comment by hhirsch** [comment]
@SGOrava We can close this issue now, right?

**Comment by SGOrava** [comment]
OK

**Comment by hhirsch** [comment]
@Sakerdot You can compile the current client with the newest bullet version. Let us know if you need assistance.
