### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by xantares** [GlPortal/glPortal#5]
hi,

could you add some integration testing using travis ?
http://docs.travis-ci.com/user/getting-started/

this way we'd know when stuff are broken, at least verify that it builds and install, please.

here's an example of travis config for another project which uses cmake:
https://github.com/xantares/ev3/blob/master/.travis.yml

**Comment by hhirsch** [comment]
We are using docker containers in travis now. This way we don't depend on their outdated environment.
