### ISSUE TITLE
Unable to get past Open Version required minimum is 3.0

### ISSUE THREAD

**Issue by Clever-Boy** [GlPortal/glPortal#50]
Compiling this code on Ubuntu linux using HD Intel Graphics 5000.  The OpenGL version is 3.3 but  when make run is executed, OpenGL version is always 0.0 

V          Window  OpenGL 0.0
E          Window  OpenGL Version 0.0 is unsupported, required minimum is 3.0

Open GL Version currently on the system.

 glxinfo | grep "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by Geertiebear** [comment]
Which branch are you using? We request a 3.0 OpenGL context on the master branch, but we changed it a while ago on RadixEngine.

**Comment by SGOrava** [comment]
this is strange...
We are using libEpoxy to provide these OpenGL things...
Main problem can be that it dont know your HW or that it detected that your HW is not supported.
Maybe you have some error in your drivers... or so thats what i found on the internet...

**Comment by Clever-Boy** [comment]
The drivers have been installed and I ran glxgears to test if it works.. and it does. I am not sure why it is always returning 0. I will have to test it on some other system. I cloned the Master branch. The RadixEngine branch I will have to dig into why the CMake is failing.  

Could not find a package configuration file provided by "CXX14" with any of
  the following names:

    CXX14Config.cmake
    cxx14-config.cmake

**Comment by SGOrava** [comment]
OK

RadixEngine branch is failing because you did not updated submodules after switching branches
Try to run
```
git submodule update --init --recursive
```

**Comment by Clever-Boy** [comment]
Thanks. It has moved ahead that error but got another error. I am not that good with CMake. Tried to investigate this error - The following REQUIRED packages have not been found *RadixEngine.  

Checked the entry in CMAKE and it says :
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/external/RadixEngine/cmake)

CMAKE_CURRENT_SOURCE_DIR is the directory where the CMakelists file is. I believe that it should pick up the correct path to the folder that is appended. Tried CMAKE_CURRENT_LIST_DIR. Still same error. I see there is a text that says it is a dirty hack just above this command in CMAKE file. Is there something else I can try. Thanks...

**Comment by SGOrava** [comment]
Can you send us cmake output / messages ?
CMkae is telling you that it was not able to find RadixEngine even when it found it.
Easiest check is to check for modules / libs json11, vhacd, serine
These libs are used i think only in RadixEngine.

**Comment by Clever-Boy** [comment]
Please find attached.. 
[CMakeError.txt](https://github.com/GlPortal/glPortal/files/536123/CMakeError.txt

Thanks.

**Comment by SGOrava** [comment]
From my point of view it looks like you did not init / update submodules in RadixEngine repository

**Comment by Clever-Boy** [comment]
Ok.  I did  git submodule update --init --recursive and ran cmake again. It did build all the files but reported that RadixEngine has not been found. I ran make and it failed for missing FreeImage.h which i will check later.

- The following REQUIRED packages have not been found:

 * RadixEngine

-- Configuring done
-- Generating done
-- Build files have been written to: /home/cleverboy/Projects/glPortal/build


/home/cleverboy/Projects/glPortal/external/RadixEngine/source/texture/TextureLoader.cpp:9:27: fatal error: FreeImagePlus.h: No such file or directory
compilation terminated.
external/RadixEngine/CMakeFiles/RadixEngine.dir/build.make:254: recipe for target 'external/RadixEngine/CMakeFiles/RadixEngine.dir/source/texture/TextureLoader.cpp.o' failed
make[2]: *** [external/RadixEngine/CMakeFiles/RadixEngine.dir/source/texture/TextureLoader.cpp.o] Error 1
CMakeFiles/Makefile2:138: recipe for target 'external/RadixEngine/CMakeFiles/RadixEngine.dir/all' failed
make[1]: *** [external/RadixEngine/CMakeFiles/RadixEngine.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Clever-Boy** [comment]
[CMakeError.txt](https://github.com/GlPortal/glPortal/files/536192/CMakeError.txt)

**Comment by SGOrava** [comment]
OK, the last error is about missing freeimageplus library.
Try to install `libfreeimageplus-dev` package

**Comment by Geertiebear** [comment]
You will always get the RadixEngine error, if you check out the travis logs you will see you get the error. As @SGOrava said, it is failing because you don't have FreeImage installed (properly)

**Comment by Clever-Boy** [comment]
I am almost there. Installed the free Image Plus library. Close to getting it compiled at 67%
There is a error in Player. cpp while the Controller is getting created. Will investigate it. Incase you have a quick suggestion. Do let me know. You have been a great help... :+1: 

/home/cleverboy/Projects/glPortal/external/RadixEngine/source/component/Player.cpp: In constructor ‘radix::Player::Player(radix::Entity&)’:
/home/cleverboy/Projects/glPortal/external/RadixEngine/source/component/Player.cpp:26:71: error: invalid new-expression of abstract class type ‘radix::KinematicCharacterController’
   controller = new KinematicCharacterController(obj, shape.get(), 0.35);
                                                                       ^ 

[CMakeError.txt](https://github.com/GlPortal/glPortal/files/536225/CMakeError.txt)

**Comment by SGOrava** [comment]
OK, the last error is becuase the library bullet was updated recently and they made changes which are incompatible with older versions.

Check issue: https://github.com/GlPortal/glPortal/issues/49

**Comment by Clever-Boy** [comment]
Excellent thanks... I will go back to Bullet version 2.83 and try again. Will close this issue once I compile and run the code. Thanks again. :100:

**Comment by Clever-Boy** [comment]
Thanks you for all the help extended.  @SGOrava and @Geertiebear.  OpenGL as you rightly said was not able to detect my card. However, I was able to compile my code successfully and happy with it.
