### ISSUE TITLE
Many errors on cmake ..

### ISSUE THREAD

**Issue by generaldave** [GlPortal/glPortal#52]
I run "cmake .." in the build folder. Everything seems to work fine up to that point. I also ran update and upgrade before starting.

First is CMake Error at CMakeLists.txt:26 (add_dependencies): Cannot add target-level dependencies to non-existent target "glportal".

Second is that gwen directory does not contain CMakeLists.txt.

Third is that vhacd-lib does not contain CMakeLists.txt.

Forth is RadixEngine not found.

I have deleted the whole glportal folder and started over twice. Get the same thing each time.

CMakeError.log is empty.

CMakeOutput.log = 
[CMakeOutput.txt](https://github.com/GlPortal/glPortal/files/734437/CMakeOutput.txt)

**Comment by hhirsch** [comment]
Check out the submodules recursively and then first go into the external/RadixEngine and get its submodules and compile it.

**Comment by hhirsch** [comment]
git submodule init
git submodule update

**Comment by SGOrava** [comment]
git submodule update --init --recursive

**Comment by Geertiebear** [comment]
We should update COMPILE.md for this.

**Comment by hhirsch** [comment]
Agreed. I was about to tell him "This is in COMPILE.md" but then checked it first and was like "wtf".

**Comment by generaldave** [comment]
I have done this:

git submodule init
git submodule update

as well as recursively.

I will try again now that the git submodule command has been changed.

**Comment by Geertiebear** [comment]
Can you make and run a simple CMakeLists.txt like this:

`cmake_minimum_required (VERSION 2.8.7)
find_package(Threads)` ? And can you give me the output of this?

**Comment by generaldave** [comment]
Sure can.

![cmake](https://cloud.githubusercontent.com/assets/7481680/22428426/efb1327e-e6d4-11e6-8290-6d1cf334cc66.png)

**Comment by SGOrava** [comment]
Do you have installed `pthread` ?
Package name should be something like `libpthread-dev` .

**Comment by generaldave** [comment]
libpthread-dev doesn't exist.

libpthread-stubs0-dev already installed.

![pthread](https://cloud.githubusercontent.com/assets/7481680/22429247/00ffd618-e6d8-11e6-9dba-71986042308a.png)

**Comment by Geertiebear** [comment]
Do you have `libc6-dev` installed?

**Comment by generaldave** [comment]
sudo apt-get install libc6-dev says "is already the newest version (2.23-0ubuntu5)."

**Comment by Geertiebear** [comment]
This may sound weird but, what version of bullet do you have installed?

**Comment by generaldave** [comment]
sudo apt-get install libbullet-dev says "already the newest version (2.83.6+dfsg-3)"

**Comment by Geertiebear** [comment]
Aha, I see, at the moment glportal requires bullet 2.85. However, I can change it so that we can support both versions, I'll do it tommorow maybe.

**Comment by generaldave** [comment]
Ok, so apparently Ubuntu 16.04 does not support bullet 2.85 being it's telling me that 2.83 is the newest version

**Comment by hhirsch** [comment]
@generaldave Usually you should be prepared to use very new versions of libraries. I used to use debian stable but had to switch to manjaro linux for the same reason. However Geerts commit should have fixed the problem for you. But be prepared that we'll prefer a newer version of a library over an older one.

**Comment by hhirsch** [comment]
@generaldave Please reopen if this problem persists.
