### ISSUE TITLE
Add teleportation

### ISSUE THREAD

**Issue by hhirsch** [GlPortal/glPortal#56]
~~Add linked teleportation entities to the game.~~
According to specification https://github.com/GlPortal/specification/blob/master/formats/map/triggers.md

- [x] Add rotation to teleport destination
- [x] Add conversion of speed vector to teleports

**Comment by hhirsch** [comment]
This can basically done as a copy and paste of what we have on stable branch.

**Comment by Geertiebear** [comment]
Isn't this already done with the teleport trigger? Or do we still need to add more stuff?

**Comment by SGOrava** [comment]
When you adding links to specification, add direct link to the right part :)

**Comment by hhirsch** [comment]
@Geertiebear I added two checklist items to my original comment. Consider the test case of destination above the portal. When you go through the portal you fall a bit and then get teleported above it again.

What I suspect will happen with the current trigger implementation is that the speed vector is discarded and as such terminal velocity is never reached. With the speed vector converted correctly I'd expect the player to maintain downwards speed until terminal velocity is reached.

**Comment by hhirsch** [comment]
@Geertiebear Added the test case fd77cd730e4b39ba4990bc19103c59e7b578e223

**Comment by Geertiebear** [comment]
Both of the checklist items work now.

**Comment by Geertiebear** [comment]
Closing this because teleportation works.

**Comment by wow2006** [comment]
- [ ] Fire one portal make the player fall.
- [ ] Player change orientation after teleporting

**Comment by hhirsch** [comment]
@wow2006 Can you make a new issue for the two points you've mentioned and close this one?
