### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by n4n0byte** [GlPortal/glPortal#73]
config: windows 10, using msys64
all of the dependencies listed on the project page were installed and
git submodule update --init --recursive
was also ran in the project directory

here is a link to the error:
 https://pastebin.com/E2Hzecqm

**Comment by hhirsch** [comment]
@n4n0byte Hello. As in our previous conversation this is no issue I am familiar with. @GlPortal/push-developers does this make any sense to you?

**Comment by SGOrava** [comment]
for some reason fpermissive is enabled

**Comment by n4n0byte** [comment]
adding set(CMAKE_CXX_FLAGS "-fpermissive") to the cmakelists file in the root directory did not work, is there anything else to attempt changing the -fpermissive setting?

**Comment by hhirsch** [comment]
@n4n0byte Did you run cmake ./ again after the change? The messages should still be there but downgraded to warnings.

**Comment by hhirsch** [comment]
No news in 12 days. You are welcome to re-open if the problem persists.
