### ISSUE TITLE
Update documentation to include libfreeimageplus-dev as dependency

### ISSUE THREAD

**Issue by priyananda** [GlPortal/glPortal#78]
I forked your project, and it was extremely easy to get it building and running - great job!

The only issue I faced was a build failure due to missing header <FreeImagePlus.h>. Turns out that libfreeimage-dev no longer includes the C++ header, which has been split into a separate package. The fix was as simple as 'apt-get install libfreeimageplus-dev'.

Can you please update the documentation to reflect this?

My setup:
Ubuntu 17.04 (x86_64)
libfreeimage-dev 3.17.0+ds1-5build1
libfreeimageplus-dev 3.17.0+ds1-5build1

**Comment by hhirsch** [comment]
I've added instructions specifically for your Ubuntu version. Thank you for reporting this.
