### ISSUE TITLE
Issue compiling in Linux Mint 18

### ISSUE THREAD

**Issue by DanielLowry** [GlPortal/glPortal#89]
Manage to configure correctly, however get the following error when trying to run make:

/home/dan/SourceCodeDownloads/GLPortal/glPortal/external/RadixEngine/source/data/texture/TextureLoader.cpp:5:27: fatal error: FreeImagePlus.h: No such file or directory
compilation terminated.
external/RadixEngine/CMakeFiles/RadixEngine.dir/build.make:1286: recipe for target 'external/RadixEngine/CMakeFiles/RadixEngine.dir/source/data/texture/TextureLoader.cpp.o' failed
make[2]: *** [external/RadixEngine/CMakeFiles/RadixEngine.dir/source/data/texture/TextureLoader.cpp.o] Error 1
CMakeFiles/Makefile2:138: recipe for target 'external/RadixEngine/CMakeFiles/RadixEngine.dir/all' failed
make[1]: *** [external/RadixEngine/CMakeFiles/RadixEngine.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Pretty sure I followed all the instructions, though please tell me if you think I have missed something.
Also installed freeimageplus via: 'sudo apt-get install libfreeimageplus3' after getting the error, but this changed nothing (after installing the above, I also configured it again before calling 'make').

Any help would be appreciated!

Thanks

**Comment by SGOrava** [comment]
it looks like you need to install library freeimageplus

**Comment by DanielLowry** [comment]
Yes, as mentioned above I tried this with 'sudo apt-get install libfreeimageplus3' but to no avail.  Any other suggestions/ways to install free image plus?

**Comment by SGOrava** [comment]
for some distributions ... you need to install development packages ... `libfreeimageplus-dev`

**Comment by ElementW** [comment]
The Mint 18 package is inherited from the Debian repositories and its dev package name is `libfreeimage-dev`. You might want to try that.

**Comment by DanielLowry** [comment]
Worked a treat with the dev package, thanks!
